<a href="https://colab.research.google.com/github/medo469/Machine-learning/blob/main/NumPy_for_Numerical_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
![NumPy Logo image](https://www.freecodecamp.org/news/content/images/size/w2000/2020/09/numpy-1.png)

___

# Before we start

- This notebook can be found in the description of the video so that you can try out the code as you watch.

- Prerequistites: Make sure you've watched these lectures first
[Linear Algebra](https://youtu.be/yOlzxzs93f8?si=_KCHfhhJaAU76w6u) and
[Python Refresher](https://www.youtube.com/watch?v=NhG_b4IMpCs&t=2688s)


# What is NumPy?

NumPy is short for Numerical Python. It's a Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is widely used in numerical computing and data analysis due to its efficiency and ease of use.

# Why NumPy over Python lists?

- Computationally more efficient, using less time and memory compared to Python lists.

- You can perform many operations more easily with NumPy than with Python lists.

- For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation Instructions

**You can install NumPy by going to your terminal or command and type:**

    #using pip
    pip install numpy

**If you have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    #using conda
    conda install numpy
    

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but we will focus on some of the most important aspects of Numpy: arrays, vectors, matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

Arrays in NumPy are similar to lists in Python.
- Elements in arrays must be of the same data type.
- Can have 1, 2, 3, or even more dimensions.

![Different Dimenstions Image](https://miro.medium.com/v2/resize:fit:817/0*y04Nh3L0aSwyGaby.png)



# Vectors vs Matrices vs Tensors
- Vectors: 1-d arrays
- Matrices: 2-d arrays (Note: a matrix can still have only one row or one column)
- Tensors: typlically 3-d and higher but can be 1-d and 2-d.


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### linspace
Return evenly spaced numbers over a specified interval.

In [8]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [9]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## eye

Creates an identity matrix

In [11]:
np.eye(57)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``. The resulting array contains random numbers that are always non-negative and uniformly spread between 0 and 1.

In [ ]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [ ]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. The resulting array contains random numbers that can be positive or negative, with most values clustering around 0.


In [ ]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

44

In [ ]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
#arr
arr.dtype

dtype('int64')

# You can do all linear algebra tranformations with numpy


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])
print(arr1+arr2)s
print(arr1-arr2)
print(arr1*arr2) #not the array multiplication it just multipies each elemnt of the array by the elemnt in the same location in the other array
print(arr1/arr2) #it divide each elemnt of the array by the elemnt in the same location in the other array

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]


### **how to do matrix multiplication then?**

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[0,12,5],[5,2,6],[9,5,8]])

np.matmul(arr1,arr2)

array([[ 37,  31,  41],
       [ 79,  88,  98],
       [121, 145, 155]])

# Great Job!